### ISSUE TITLE
Exclude ZIP Archives (on Dropbox) from Incorrectly Getting Embedded

### ISSUE THREAD

**Issue by KnaperYaden** [codaworks/ivelt-media#1]
I posted a Dropbox link to a ZIP archive, and it got a player embedded as if it's a video.

See for example in https://www.ivelt.com/forum/viewtopic.php?p=5069799#p5069799

![image](https://github.com/codaworks/ivelt-media/assets/87161728/b0bf9764-bc2a-41dc-a3e2-507e6d3d4686)

Either don't have it do anything for ZIP, or - if possible - have a preview of the files in the archive.

**Comment by mordechaim** [comment]
I'm aware of this issue. The only way around this would be to do a HEAD request for each Dropbox link prior to adding the video element. This way I can check the `content-type` header.

I really hope not to have to resort to this.

Let me test what other potential solutions I might come up with.

**Comment by KnaperYaden** [comment]
The `.zip` in the URL itself can't be used to filter it out before anything?

**Comment by mordechaim** [comment]
Ah I didn't notice the file name is in the URL. You're right.

Now I can even properly embed PDFs as well. Thanks!
